services:
  mysql:
    image: mysql:8-oracle
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: dummypassword
      MYSQL_USER: user
      MYSQL_PASSWORD: dummypassword
      MYSQL_DATABASE: pos-system-database
    ports:
      - "3306:3306"
