spring.application.name=POS-System


server.port=8080
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://${MYSQL_HOST:localhost}:3306/pos-system-database
spring.datasource.username=user
spring.datasource.password=dummypassword
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

#secret key
jwt.secret=6Qn2iS4W9zLp8Fk3HxN8aBcD7YeT1RmVvA5KxZ2PwM8LsN4QeJ7HrC1UyF6ZdB3Xa
jwt.expiration=86400000